/*
 * File: app/model/FiscalDataLogModel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.FiscalDataLogModel', {
    extend: 'Ext.data.Model',

    idProperty: 'log_id',

    fields: [
        {
            name: 'iso'
        },
        {
            name: 'currency'
        },
        {
            name: 'year'
        },
        {
            name: 'debt_exports'
        },
        {
            name: 'public_plus_private_debt_gdp'
        },
        {
            name: 'domestic_plus_external_debt_gdp'
        },
        {
            name: 'debt_gnp'
        },
        {
            name: 'currency_crisis'
        },
        {
            name: 'inflation_crisis'
        },
        {
            name: 'stock_market_crash'
        },
        {
            name: 'soverign_debt_crisis_domestic'
        },
        {
            name: 'sovereign_debt_crisis_external'
        },
        {
            name: 'banking_crisis'
        },
        {
            name: 'crisis_tally'
        },
        {
            name: 'gov_revenue'
        },
        {
            name: 'gov_spending'
        },
        {
            name: 'gov_debt'
        },
        {
            name: 'int_on_gov_debt'
        },
        {
            name: 'Short_term_interest_rate'
        },
        {
            name: 'gdp'
        },
        {
            name: 'gov_bond_yield'
        },
        {
            name: 'price_index'
        },
        {
            name: 'int_revenue'
        },
        {
            name: 'outstanding_bond'
        },
        {
            name: 'avg_maturity'
        },
        {
            name: 'int_expense_general'
        },
        {
            name: 'gov_revenue_general'
        },
        {
            name: 'gov_spending_general'
        },
        {
            name: 'source'
        },
        {
            name: 'income_tax_revenue'
        },
        {
            name: 'consumption_tax_revenue'
        },
        {
            name: 'military_spending'
        },
        {
            name: 'social_insurance_spending'
        },
        {
            name: 'health_expenditure'
        },
        {
            name: 'comments'
        },
        {
            name: 'user_comment'
        },
        {
            name: 'domestic_debt'
        },
        {
            name: 'foreign_debt'
        },
        {
            name: 'changed_by'
        },
        {
            name: 'change_date'
        },
        {
            name: 'action'
        },
        {
            name: 'status'
        },
        {
            name: 'id'
        },
        {
            name: 'active'
        },
        {
            name: 'verified_by'
        },
        {
            name: 'verification_date'
        },
        {
            name: 'log_id'
        }
    ]
});