/*
 * File: app/model/FiscalDataModel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.FiscalDataModel', {
    extend: 'Ext.data.Model',

    idProperty: 'id',

    fields: [
        {
            name: 'iso'
        },
        {
            name: 'currency'
        },
        {
            name: 'year',
            type: 'string'
        },
        {
            name: 'gov_revenue',
            sortType: 'asFloat',
            type: 'float',
            useNull: false
        },
        {
            name: 'gov_spending',
            sortType: 'asFloat',
            type: 'float'
        },
        {
            name: 'gov_debt',
            sortType: 'asFloat',
            type: 'float'
        },
        {
            name: 'int_on_gov_debt',
            sortType: 'asFloat',
            type: 'float'
        },
        {
            name: 'currency_crisis',
            sortType: 'asFloat',
            type: 'float'
        },
        {
            name: 'inflation_crisis',
            sortType: 'asFloat',
            type: 'float'
        },
        {
            name: 'soverign_debt_crisis_domestic',
            sortType: 'asFloat',
            type: 'float'
        },
        {
            name: 'sovereign_debt_crisis_external',
            sortType: 'asFloat',
            type: 'float'
        },
        {
            name: 'domestic_plus_external_debt_gdp',
            sortType: 'asFloat',
            type: 'float'
        },
        {
            name: 'public_plus_private_debt_gdp',
            sortType: 'asFloat',
            type: 'float'
        },
        {
            name: 'debt_gnp',
            sortType: 'asFloat',
            type: 'float'
        },
        {
            name: 'source',
            sortType: 'asUCString',
            type: 'string'
        },
        {
            name: 'comments',
            type: 'string'
        },
        {
            name: 'user_comment',
            type: 'string'
        },
        {
            name: 'status'
        },
        {
            name: 'changed_by'
        },
        {
            name: 'change_date'
        },
        {
            name: 'action'
        },
        {
            name: 'id',
            type: 'int'
        }
    ]
});