/*
 * File: app/store/LogStore.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.LogStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.FiscalDataLogModel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'MyJsonStore2',
            model: 'MyApp.model.FiscalDataLogModel',
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json',
                    idProperty: 'log_id'
                },
                writer: {
                    type: 'json',
                    writeAllFields: false,
                    allowSingle: false
                }
            },
            listeners: {
                update: {
                    fn: me.onJsonstoreUpdate,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onJsonstoreUpdate: function(abstractstore, record, operation, modifiedFieldNames, options) {
        //GLOB.updateLogRecord();
    }

});