/*
 * File: app/view/FiscalDataLogGrid.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.FiscalDataLogGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.fiscaldataloggrid',

    id: 'fiscalDataLogGrid',
    animCollapse: false,
    header: false,
    title: 'Audit trail',
    hideHeaders: false,
    sortableColumns: false,
    store: 'LogStore',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            plugins: [
                Ext.create('Ext.grid.plugin.CellEditing', {
                    ptype: 'cellediting',
                    clicksToEdit: 1
                })
            ],
            dockedItems: [
                {
                    xtype: 'container',
                    dock: 'top',
                    height: 30,
                    style: '{\n    background-color:white;\n    border-top: 1px solid silver;\n}',
                    width: 100,
                    layout: {
                        align: 'middle',
                        padding: '0 0 0 0 0',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'button',
                            margins: '0 6 0 0',
                            id: 'refreshFiscalDataGridLogButton',
                            icon: 'images/view_refresh.png',
                            tooltip: 'Refresh',
                            listeners: {
                                click: {
                                    fn: me.onRefreshFiscalDataGridLogButtonClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'label',
                            style: 'color:#333;  font-size:11px;',
                            text: 'AUDIT TRAIL'
                        },
                        {
                            xtype: 'container',
                            flex: 1
                        },
                        {
                            xtype: 'container',
                            html: '<img src="images/gtk_close.png" style="width:16px; height:16px;cursor:pointer;" onclick="GLOB.hideHistoryPanel()" >'
                        }
                    ]
                }
            ],
            viewConfig: {
                getRowClass: function(record, rowIndex, rowParams, store) {
                    return GLOB.getRowStatus(record);
                },
                stripeRows: false,
                listeners: {
                    added: {
                        fn: me.onGridviewAdded,
                        scope: me
                    }
                }
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    width: 60,
                    dataIndex: 'id',
                    text: 'Id'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'log_id',
                    text: 'Log_id'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return GLOB.getActiveRendererString(value, metaData, record);
                    },
                    width: 60,
                    dataIndex: 'active',
                    text: 'Active'
                },
                {
                    xtype: 'actioncolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return GLOB.getStatusRendererString(value, metaData, record);



                    }
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'status',
                    text: 'Status'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'action',
                    text: 'Action'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'iso',
                    text: 'Iso'
                },
                {
                    xtype: 'gridcolumn',
                    width: 46,
                    dataIndex: 'year',
                    text: 'Year'
                },
                {
                    xtype: 'gridcolumn',
                    width: 61,
                    dataIndex: 'currency',
                    text: 'Currency'
                },
                {
                    xtype: 'numbercolumn',
                    align: 'right',
                    dataIndex: 'gov_revenue',
                    text: 'Government revenue'
                },
                {
                    xtype: 'numbercolumn',
                    align: 'right',
                    dataIndex: 'gov_spending',
                    text: 'Government spending'
                },
                {
                    xtype: 'numbercolumn',
                    align: 'right',
                    dataIndex: 'gov_debt',
                    text: 'Government debt'
                },
                {
                    xtype: 'numbercolumn',
                    align: 'right',
                    dataIndex: 'int_on_gov_debt',
                    text: 'Interest Expense'
                },
                {
                    xtype: 'numbercolumn',
                    align: 'right',
                    dataIndex: 'soverign_debt_crisis_domestic',
                    text: 'Domestic Debt Crisis',
                    format: '0,000'
                },
                {
                    xtype: 'numbercolumn',
                    align: 'right',
                    dataIndex: 'sovereign_debt_crisis_external',
                    text: 'Foreign Debt Crisis',
                    format: '0,000'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        if (!value) return '';
                        if (value.length>0) return "comments..";
                        return '';
                    },
                    dataIndex: 'user_comment',
                    text: 'User Comments'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'debt_exports',
                    text: 'Debt_exports'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'public_plus_private_debt_gdp',
                    text: 'Public_plus_private_debt_gdp'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'domestic_plus_external_debt_gdp',
                    text: 'Domestic_plus_external_debt_gdp'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'debt_gnp',
                    text: 'Debt_gnp'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'currency_crisis',
                    text: 'Currency_crisis'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'inflation_crisis',
                    text: 'Inflation_crisis'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'stock_market_crash',
                    text: 'Stock_market_crash'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'banking_crisis',
                    text: 'Banking_crisis'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'crisis_tally',
                    text: 'Crisis_tally'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'Short_term_interest_rate',
                    text: 'Short_term_interest_rate'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'gdp',
                    text: 'Gdp'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'gov_bond_yield',
                    text: 'Gov_bond_yield'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'price_index',
                    text: 'Price_index'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'int_revenue',
                    text: 'Int_revenue'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'outstanding_bond',
                    text: 'Outstanding_bond'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'avg_maturity',
                    text: 'Avg_maturity'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'int_expense_general',
                    text: 'Int_expense_general'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'gov_revenue_general',
                    text: 'Gov_revenue_general'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'gov_spending_general',
                    text: 'Gov_spending_general'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'source',
                    text: 'Source'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'income_tax_revenue',
                    text: 'Income_tax_revenue'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'consumption_tax_revenue',
                    text: 'Consumption_tax_revenue'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'military_spending',
                    text: 'Military_spending'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'social_insurance_spending',
                    text: 'Social_insurance_spending'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'health_expenditure',
                    text: 'Health_expenditure'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'comments',
                    text: 'Comments'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'domestic_debt',
                    text: 'Domestic_debt'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'foreign_debt',
                    text: 'Foreign_debt'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'changed_by',
                    text: 'Changed_by'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'change_date',
                    text: 'Change_date'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'verified_by',
                    text: 'Verified_by'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'verification_date',
                    text: 'Verification_date'
                }
            ],
            listeners: {
                beforeedit: {
                    fn: me.onFiscalDataLogGridBeforeEdit,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onRefreshFiscalDataGridLogButtonClick: function(button, e, options) {
        GLOB.refreshFiscalDataLogGrid();
    },

    onGridviewAdded: function(abstractcomponent, container, pos, options) {
        //this.preserveScrollOnRefresh=true;

    },

    onFiscalDataLogGridBeforeEdit: function(editor, e, options) {
        return GLOB.getUserName()!='' ;
    }

});