/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'MyApp.view.FiscalDataLogGrid'
    ],

    hidden: false,
    style: 'background-color:#FFF;',
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    region: 'north',
                    split: false,
                    splitterResize: false,
                    frame: false,
                    hidden: false,
                    id: 'headerContainer',
                    loader: {
                        url: 'header.html',
                        autoLoad: false
                    },
                    layout: {
                        align: 'stretch',
                        padding: '0 0 5 0',
                        type: 'vbox'
                    },
                    items: [
                        {
                            xtype: 'label',
                            style: 'color:#333; font-size:12px; ',
                            text: 'SOVEREIGN FISCAL DATA'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    floatable: false,
                    region: 'center',
                    border: 0,
                    floating: false,
                    frame: false,
                    id: 'container',
                    layout: {
                        type: 'card'
                    },
                    bodyBorder: false,
                    frameHeader: false,
                    header: false,
                    hideCollapseTool: false,
                    title: 'Sovereign Fiscal Data',
                    items: [
                        {
                            xtype: 'container',
                            style: 'background-color:white;',
                            layout: {
                                type: 'border'
                            },
                            items: [
                                {
                                    xtype: 'toolbar',
                                    region: 'north',
                                    border: '1 1 0 1',
                                    frame: false,
                                    style: '{\nbackground-color: #FFFFFF;\nbackground-image:none;\n}',
                                    layout: {
                                        padding: 2,
                                        type: 'hbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            margins: '0 0 0 0',
                                            id: 'refreshFiscalDataGridButton',
                                            icon: 'images/view_refresh.png',
                                            tooltip: 'Refresh',
                                            listeners: {
                                                click: {
                                                    fn: me.onRefreshFiscalDataGridButtonClick1,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'combobox',
                                            id: 'cmbCountry',
                                            width: 178,
                                            fieldLabel: 'Country',
                                            hideLabel: true,
                                            displayField: 'country',
                                            queryMode: 'local',
                                            store: 'CountriesJsonStore',
                                            valueField: 'iso',
                                            listeners: {
                                                select: {
                                                    fn: me.onCmbCountrySelect,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'btnEdit',
                                            allowDepress: false,
                                            enableToggle: false,
                                            icon: 'images/edit16.png',
                                            pressed: false,
                                            text: 'Edit',
                                            tooltip: '<b>Edit selected record</b><hr/>\nAnother way is to\n<b>Double click</b> on a record.\n<hr/>\nYou must be logined in to edit records.',
                                            listeners: {
                                                click: {
                                                    fn: me.onBtnEditClick,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'btnShowComments',
                                            icon: 'images/comment2.png',
                                            text: 'Show comments',
                                            tooltip: '<b>Show user comments to the selected record</b>',
                                            listeners: {
                                                click: {
                                                    fn: me.onBtnShowCommentsClick,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            disabled: false,
                                            id: 'btnShowHistory',
                                            icon: 'images/text_list_bullets.png',
                                            text: 'Show audit trail',
                                            tooltip: '<b>Show log of changes to the selected record</b><br>\n<hr/>\nYou must be logined in and have "<b>moderator</b>" privileges to edit the log.\n<hr/>\nContact Marc Joffe <a href="mailto:marc@publicsectorcredit.org">marc@publicsectorcredit.org</a> if you want to join.',
                                            listeners: {
                                                click: {
                                                    fn: me.onBtnShowHistoryClick,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'tbspacer',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'button',
                                            floating: false,
                                            frame: true,
                                            id: 'btnExport',
                                            icon: 'images/browser_download.png',
                                            tooltip: 'Export data to Excel (CSV)',
                                            listeners: {
                                                click: {
                                                    fn: me.onBtnExportClick,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'btnLeaveComment',
                                            icon: 'images/bubble16.png',
                                            tooltip: 'Leave a general comment',
                                            listeners: {
                                                click: {
                                                    fn: me.onBtnLeaveCommentClick,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'container',
                                            loader: {
                                                url: '/getloginlink',
                                                autoLoad: true
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    region: 'center',
                                    frame: false,
                                    id: 'gridFiscalData',
                                    bodyBorder: false,
                                    collapsed: false,
                                    collapsible: false,
                                    frameHeader: false,
                                    header: false,
                                    hideCollapseTool: true,
                                    title: 'Sovereign Fiscal Data',
                                    titleCollapse: false,
                                    hideHeaders: false,
                                    store: 'FiscalDataStore',
                                    verticalScroller: {
                                        // xtype: 'paginggridscroller',
                                        // activePrefetch: false
                                        trailingBufferZone: 10,
                                        // Keep 200 records buffered in memory behind scroll
                                        leadingBufferZone: 10// Keep 5000 records buffered in memory ahead of scroll
                                    },
                                    viewConfig: {
                                        getRowClass: function(record, rowIndex, rowParams, store) {
                                            return GLOB.getRowStatus(record);


                                        },
                                        trackOver: false,
                                        stripeRows: false
                                    },
                                    columns: [
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'id',
                                            text: 'id',
                                            format: '0,000'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            editRenderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                return "";
                                            },
                                            width: 135,
                                            dataIndex: 'change_date',
                                            text: 'Change Date'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            dataIndex: 'status',
                                            text: 'status'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            dataIndex: 'action',
                                            text: 'Action'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 54,
                                            align: 'right',
                                            dataIndex: 'year',
                                            text: 'Year'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 68,
                                            dataIndex: 'currency',
                                            text: 'Currency'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            align: 'right',
                                            dataIndex: 'gov_revenue',
                                            text: 'Government Revenue',
                                            editor: {
                                                xtype: 'textfield'
                                            }
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            align: 'right',
                                            dataIndex: 'gov_spending',
                                            text: 'Government Spending',
                                            editor: {
                                                xtype: 'textfield'
                                            }
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            align: 'right',
                                            dataIndex: 'gov_debt',
                                            text: 'Government Debt',
                                            editor: {
                                                xtype: 'textfield'
                                            }
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            align: 'right',
                                            dataIndex: 'int_on_gov_debt',
                                            text: 'Interest Expense',
                                            editor: {
                                                xtype: 'textfield'
                                            }
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: false,
                                            align: 'right',
                                            dataIndex: 'soverign_debt_crisis_domestic',
                                            text: 'Domestic Debt Crisis',
                                            format: '0,000',
                                            editor: {
                                                xtype: 'textfield'
                                            }
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: false,
                                            align: 'right',
                                            dataIndex: 'sovereign_debt_crisis_external',
                                            text: 'Foreign Debt Crisis',
                                            format: '0,000',
                                            editor: {
                                                xtype: 'textfield'
                                            }
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            editRenderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                return '<button class="addCommentButton" onclick="GLOB.showCommentWindow()">'+
                                                '<img src="images/comment2.png" >'+
                                                'Add comment</button>';

                                            },
                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                if (!value) return '';
                                                if (value.length>0) return "comm..";
                                                return '';
                                            },
                                            id: 'userCommentsId',
                                            itemId: 'userCommentsItemId',
                                            defaultWidth: 200,
                                            dataIndex: 'user_comment',
                                            text: 'User Comments'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            editRenderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                return "";
                                            },
                                            style: 'white-space:nowrap;',
                                            defaultWidth: 200,
                                            dataIndex: 'comments',
                                            text: 'Comments'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: false,
                                            align: 'right',
                                            dataIndex: 'currency_crisis',
                                            text: 'Currency Crisis',
                                            format: '0,000'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: false,
                                            align: 'right',
                                            dataIndex: 'inflation_crisis',
                                            text: 'Inflation Crisis',
                                            format: '0,000'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: false,
                                            align: 'right',
                                            dataIndex: 'domestic_plus_external_debt_gdp',
                                            text: 'Domestic &amp; External Debt/GDP Ratio'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: false,
                                            align: 'right',
                                            dataIndex: 'public_plus_private_debt_gdp',
                                            text: 'Private Debt/GDP Ratio'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: false,
                                            align: 'right',
                                            dataIndex: 'debt_gnp',
                                            text: 'Debt/GNP Ratio'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            dataIndex: 'source',
                                            text: 'Source',
                                            editor: {
                                                xtype: 'textareafield'
                                            }
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'changed_by',
                                            text: 'Changed by'
                                        }
                                    ],
                                    listeners: {
                                        select: {
                                            fn: me.onGridFiscalDataSelect,
                                            scope: me
                                        },
                                        beforeedit: {
                                            fn: me.onGridFiscalDataBeforeEdit,
                                            scope: me
                                        },
                                        edit: {
                                            fn: me.onGridFiscalDataEdit,
                                            scope: me
                                        }
                                    },
                                    selModel: Ext.create('Ext.selection.RowModel', {

                                    }),
                                    plugins: [
                                        Ext.create('Ext.grid.plugin.RowEditing', {
                                            ptype: 'rowediting',
                                            pluginId: 'rowEditor',
                                            clicksToMoveEditor: 1
                                        })
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    collapseMode: 'mini',
                                    region: 'east',
                                    split: true,
                                    border: '1 1 1 0',
                                    hidden: true,
                                    hideMode: 'visibility',
                                    id: 'panelRecordComments',
                                    width: 250,
                                    layout: {
                                        type: 'border'
                                    },
                                    bodyStyle: '{\n    background-color:white;\n}',
                                    animCollapse: false,
                                    closable: false,
                                    closeAction: 'hide',
                                    collapsed: false,
                                    collapsible: false,
                                    frameHeader: false,
                                    header: false,
                                    hideCollapseTool: false,
                                    title: 'User comments to the record',
                                    titleCollapse: false,
                                    items: [
                                        {
                                            xtype: 'container',
                                            region: 'north',
                                            height: 24,
                                            style: '{\n    border-bottom: 1px solid silver;\n}',
                                            layout: {
                                                align: 'middle',
                                                padding: '0 1 0 8 0',
                                                type: 'hbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    style: 'color:#333; font-size:11px;',
                                                    text: 'USERS COMMENTS TO THE RECORD'
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'container',
                                                    html: '<img src="images/gtk_close.png" style="width:16px; height:16px;cursor:pointer;" onclick="GLOB.hideCommentsPanel()" >'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            region: 'center',
                                            split: true,
                                            id: 'commentContainer',
                                            padding: 5,
                                            style: '{\n    background-color:#FFF;\n    border-bottom:1px solid silver;\n}',
                                            autoScroll: true
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 0.4,
                                            region: 'south',
                                            split: true,
                                            height: 150,
                                            maxHeight: 200,
                                            minHeight: 50,
                                            layout: {
                                                align: 'stretch',
                                                type: 'vbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textareafield',
                                                    flex: 1,
                                                    id: 'newCommentTextArea',
                                                    fieldLabel: 'Label',
                                                    hideLabel: true
                                                },
                                                {
                                                    xtype: 'container',
                                                    layout: {
                                                        align: 'stretch',
                                                        pack: 'end',
                                                        padding: '0 4 4 0',
                                                        type: 'hbox'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            icon: 'images/comment2.png',
                                                            text: 'Add',
                                                            listeners: {
                                                                click: {
                                                                    fn: me.onButtonClick,
                                                                    scope: me
                                                                }
                                                            }
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fiscaldataloggrid',
                                    height: 200,
                                    hidden: true,
                                    flex: 0.7,
                                    region: 'south',
                                    split: true
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            hidden: false,
                            html: '<iframe style="width:100%; height:100%; border:none" src="comments/comments.html"></iframe>',
                            layout: {
                                type: 'absolute'
                            },
                            collapsed: false,
                            header: false,
                            hideCollapseTool: true,
                            title: 'Leave a comment',
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    x: 317,
                                    y: 209,
                                    dock: 'top',
                                    style: '{\nbackground-color: white; \nbackground-image:none;\n}',
                                    layout: {
                                        pack: 'end',
                                        padding: 2,
                                        type: 'hbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            id: 'btnShowFiscalData',
                                            text: 'Back to Fiscal Data',
                                            listeners: {
                                                click: {
                                                    fn: me.onBtnShowFiscalDataClick,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    region: 'south',
                    id: 'footerContainer',
                    loader: {
                        url: 'footer.html',
                        autoLoad: true
                    },
                    padding: '5 0 2 0'
                }
            ]
        });

        me.callParent(arguments);
    },

    onRefreshFiscalDataGridButtonClick1: function(button, e, options) {
        GLOB.refreshFiscalDataGrid();
    },

    onCmbCountrySelect: function(combo, records, options) {
        var v=combo.getValue();
        var store=Ext.getStore("FiscalDataStore");
        var proxy=store.getProxy();
        proxy.url=GLOB.SOVDEF_URL+v;
        store.load();
        GLOB.saveState();
        GLOB.clearPanels();
    },

    onBtnEditClick: function(button, e, options) {

        var lastSelected=GLOB.getSelectedRecord();
        if (! lastSelected ) 
        {
            alert ("Please select a record first.\nOr Double-Click on a record to start editing.");
            return;
        }

        var grid=Ext.getCmp("gridFiscalData");
        var editor=grid.getPlugin("rowEditor");
        editor.startEdit(lastSelected,0);

    },

    onBtnShowCommentsClick: function(button, e, options) {
        var commentPanel=Ext.getCmp("panelRecordComments");
        if (commentPanel.isHidden()) 
        {
            commentPanel.show();
            button.setText("Hide comments");
            var record=GLOB.getSelectedRecord();
            if (record)
            {
                GLOB.showTextOnTheCommentPanel(record.raw.user_comment);
            }
        }
        else
        {
            commentPanel.hide();
            button.setText("Show comments");
        }    

        GLOB.saveState();
    },

    onBtnShowHistoryClick: function(button, e, options) {
        var cont=Ext.getCmp("fiscalDataLogGrid");

        if (cont.hidden) 
        {
            cont.show();
            GLOB.showFiscalDataLog();
            button.setText("Hide audit trail");
        }
        else
        {
            cont.hide();
            button.setText("Show audit trail");
        }

        GLOB.saveState();
    },

    onBtnExportClick: function(button, e, options) {
        GLOB.exportToExcel();
    },

    onBtnLeaveCommentClick: function(button, e, options) {
        Ext.getCmp('container').getLayout().setActiveItem(1);
    },

    onGridFiscalDataSelect: function(selModel, record, index, options) {
        GLOB.showTextOnTheCommentPanel(record.raw.user_comment);
        GLOB.showFiscalDataLogLater();
    },

    onGridFiscalDataBeforeEdit: function(editor, e, options) {
        return GLOB.getUserName()!='' ;
    },

    onGridFiscalDataEdit: function(editor, e, options) {
        GLOB.saveChangesToFiscalData();
    },

    onButtonClick: function(button, e, options) {
        GLOB.addCommentHandler();
    },

    onBtnShowFiscalDataClick: function(button, e, options) {
        Ext.getCmp('container').getLayout().setActiveItem(0);
    }

});